# Generated by Django 4.1.4 on 2023-02-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leads_File",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="files")),
                ("file_name", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "leads_file",
            },
        ),
        migrations.CreateModel(
            name="Sources",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "leads_file_Source",
            },
        ),
        migrations.CreateModel(
            name="user_profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("status", models.CharField(max_length=10)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="User_Otp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("otp", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leads.user_profile",
                    ),
                ),
            ],
            options={
                "db_table": "user_otp",
            },
        ),
        migrations.CreateModel(
            name="Redundant_data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                ("redund_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leads.leads_file",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leads.sources",
                    ),
                ),
            ],
            options={
                "db_table": "Redundant_data",
            },
        ),
        migrations.AddField(
            model_name="leads_file",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="leads.sources"
            ),
        ),
        migrations.CreateModel(
            name="Leads",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=150, null=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "debt_amount",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                ("opt_in_ip", models.CharField(blank=True, max_length=150, null=True)),
                ("cost", models.CharField(blank=True, max_length=150, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("import_date", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leads.sources",
                    ),
                ),
            ],
            options={
                "db_table": "leads_data",
            },
        ),
    ]
