from django.urls import path
from .views import*

urlpatterns = [
    path('home/', home, name='home'),
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
    # path('tra/',tra, name='tra'),
    path('forget_password/', forget_password, name='forget_password'),
    path('reset-password/', reset_password, name="reset-password"),
    # path('source_data/',source_data, name='source_data'),
    # path('del_source_data/',del_source_data, name='del_source_data'),
    # path('display/',display, name='display'),
    path('add_admin/', add_admin, name="add_admin"),
    path('user_register/',user_register, name='user_register'),
    path('del_user/<int:pk>/',del_user,name='del_user'),
    path('search_user/',search_user, name='search_user'),
    path('update_user/',update_user, name='update_user'),
    path('leads/',leads, name='leads'),
    path('lead/<int:id>/', lead_details, name="lead_details"),
    path('del_lead/<int:pk>/',del_lead, name='del_lead'),
    # path('pop_up_lead/',pop_up_lead, name="pop_up_lead"),
    path('search_lead/',search_lead, name='search_lead'),
    path('sources/',sources, name='sources'),
    path('source-detail/',source_detail, name='source_detail'),
    path('user/', user, name='user'),
    path('import/', imports, name='imports'),
    path('source/<int:pk>/', del_source, name="del_source"),
    path('update_source/', update_source, name="update_source"),
    path('search_source/',search_source, name='search_source'),
    path("save_leads_column/", save_leads_column, name="save_leads_column"),
    path("page_not_found_view/", page_not_found_view, name="page_not_found_view"),
    path("page_server_error_view/", page_server_error_view, name="page_server_error_view"),
    path("file/", file, name="file"),
    path("file/<str:file_name>/", file_detail, name="file_detail"),
    path('seach-file/', search_file, name="search-file"),
    path('export_lead/', export_lead, name="export_lead"),
]
